const sampleModels = {
  duck: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/Duck/glTF-Binary/Duck.glb',
  box: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/Box/glTF-Binary/Box.glb',
  helmet:
    'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb',
  lantern:
    'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/Lantern/glTF-Binary/Lantern.glb',
  avocado:
    'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/Avocado/glTF-Binary/Avocado.glb',
  bottle:
    'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/WaterBottle/glTF-Binary/WaterBottle.glb',
  corset:
    'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/Corset/glTF-Binary/Corset.glb',
};

export const MODELS = [
  {
    id: 1,
    name: 'Low Poly Dragon',
    title: 'Low Poly Dragon',
    price: '$38.00',
    priceValue: 38,
    likes: 1280,
    rating: 4.9,
    reviews: 186,
    downloads: 1184,
    views: '32.4k',
    creator: 'Sofia Beasts',
    verified: true,
    category: 'Creatures',
    image: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.duck,
    featured: true,
    trending: true,
    staffPick: true,
    description:
      'A stylized dragon built for fast iteration in fantasy games, cinematics, and tabletop scenes. Includes clean topology, separated wings, and texture-ready material groups.',
    polygons: 8420,
    vertices: 6320,
    textures: '2K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: true,
    animated: false,
    lowPoly: true,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-04-18',
    tags: ['Dragon', 'Creature', 'Low Poly', 'Fantasy', 'PBR'],
  },
  {
    id: 2,
    name: 'Medieval Castle Tower',
    title: 'Medieval Castle Tower',
    price: '$45.00',
    priceValue: 45,
    likes: 940,
    rating: 4.8,
    reviews: 92,
    downloads: 761,
    views: '28.1k',
    creator: 'Omar Builds',
    verified: true,
    category: 'Environment',
    image: 'https://images.unsplash.com/photo-1634152962476-4b8a00e1915c?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.box,
    featured: true,
    trending: true,
    staffPick: false,
    description:
      'A modular tower kit with battlements, doors, stairs, and stone material variations for rapidly building fortress scenes.',
    polygons: 15200,
    vertices: 12100,
    textures: '4K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: false,
    animated: false,
    lowPoly: false,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-04-02',
    tags: ['Castle', 'Medieval', 'Environment', 'Modular', 'PBR'],
  },
  {
    id: 3,
    name: 'Sci-Fi Spaceship',
    title: 'Sci-Fi Spaceship',
    price: '$32.00',
    priceValue: 32,
    likes: 1560,
    rating: 4.7,
    reviews: 144,
    downloads: 1022,
    views: '41.8k',
    creator: 'Kenji Makes',
    verified: true,
    category: 'Vehicles',
    image: 'https://images.unsplash.com/photo-1614729939124-032f0b56c9ce?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.corset,
    featured: true,
    trending: true,
    staffPick: true,
    description:
      'A compact hard-surface ship asset with cockpit silhouettes, emissive panel groups, and optimized LOD-ready mesh density.',
    polygons: 18500,
    vertices: 14200,
    textures: '4K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: false,
    animated: false,
    lowPoly: false,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-03-27',
    tags: ['Spaceship', 'Vehicle', 'Sci-Fi', 'Hard Surface', 'Game Ready'],
  },
  {
    id: 4,
    name: 'Fantasy Sword',
    title: 'Fantasy Sword',
    price: '$12.00',
    priceValue: 12,
    likes: 730,
    rating: 4.8,
    reviews: 76,
    downloads: 1440,
    views: '19.9k',
    creator: 'Lina Forge',
    verified: true,
    category: 'Weapons',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.helmet,
    featured: true,
    trending: false,
    staffPick: true,
    description:
      'A hero weapon with rune-ready UV islands, crisp silhouette reads, and material IDs for blade, wrap, and gem details.',
    polygons: 3200,
    vertices: 2100,
    textures: '2K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: false,
    animated: false,
    lowPoly: true,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-04-24',
    tags: ['Sword', 'Weapon', 'Fantasy', 'Low Poly', 'PBR'],
  },
  {
    id: 5,
    name: 'Racing Car',
    title: 'Racing Car',
    price: '$26.00',
    priceValue: 26,
    likes: 1112,
    rating: 4.6,
    reviews: 83,
    downloads: 638,
    views: '22.7k',
    creator: 'Kenji Makes',
    verified: true,
    category: 'Vehicles',
    image: 'https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.bottle,
    featured: true,
    trending: false,
    staffPick: false,
    description:
      'A streamlined race car body with separated wheel pivots, clean naming, and materials ready for player customization.',
    polygons: 22000,
    vertices: 18500,
    textures: '4K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: true,
    animated: false,
    lowPoly: false,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-02-11',
    tags: ['Car', 'Vehicle', 'Racing', 'Game Ready'],
  },
  {
    id: 6,
    name: 'Knight Character',
    title: 'Knight Character',
    price: '$24.00',
    priceValue: 24,
    likes: 856,
    rating: 4.7,
    reviews: 68,
    downloads: 904,
    views: '18.5k',
    creator: 'Aria Voxel',
    verified: true,
    category: 'Characters',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.duck,
    featured: false,
    trending: true,
    staffPick: false,
    description:
      'A fully rigged knight with armor layers, simple facial controls, and baked texture variants for heroic and worn looks.',
    polygons: 12800,
    vertices: 9600,
    textures: '2K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: true,
    animated: true,
    lowPoly: true,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-04-28',
    tags: ['Knight', 'Character', 'Rigged', 'Animated', 'Low Poly'],
  },
  {
    id: 7,
    name: 'Robot Companion',
    title: 'Robot Companion',
    price: '$28.00',
    priceValue: 28,
    likes: 674,
    rating: 4.5,
    reviews: 54,
    downloads: 511,
    views: '13.6k',
    creator: 'Ravi Craft',
    verified: false,
    category: 'Characters',
    image: 'https://images.unsplash.com/photo-1633398361623-b87e22135c36?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.lantern,
    featured: false,
    trending: false,
    staffPick: false,
    description:
      'A friendly modular robot with swappable limbs, readable silhouettes, and material slots for team color variants.',
    polygons: 8900,
    vertices: 7200,
    textures: '2K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: true,
    animated: false,
    lowPoly: true,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-03-19',
    tags: ['Robot', 'Character', 'Companion', 'Rigged'],
  },
  {
    id: 8,
    name: 'Fantasy Tree',
    title: 'Fantasy Tree',
    price: '$8.00',
    priceValue: 8,
    likes: 520,
    rating: 4.6,
    reviews: 42,
    downloads: 1608,
    views: '12.3k',
    creator: 'Omar Builds',
    verified: true,
    category: 'Environment',
    image: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.avocado,
    featured: false,
    trending: false,
    staffPick: false,
    description:
      'A stylized tree asset with hand-authored color groups, flexible scale ranges, and quick biome recoloring.',
    polygons: 5600,
    vertices: 4200,
    textures: '2K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: false,
    animated: false,
    lowPoly: true,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-01-30',
    tags: ['Tree', 'Environment', 'Fantasy', 'Low Poly'],
  },
  {
    id: 9,
    name: 'Laser Gun',
    title: 'Laser Gun',
    price: '$9.00',
    priceValue: 9,
    likes: 446,
    rating: 4.5,
    reviews: 35,
    downloads: 1189,
    views: '8.8k',
    creator: 'Lina Forge',
    verified: true,
    category: 'Weapons',
    image: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.helmet,
    featured: false,
    trending: false,
    staffPick: false,
    description:
      'A compact laser sidearm with emissive strips, grouped moving parts, and texture masks for color customization.',
    polygons: 4200,
    vertices: 3100,
    textures: '2K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: false,
    animated: true,
    lowPoly: true,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-04-01',
    tags: ['Laser', 'Weapon', 'Sci-Fi', 'Animated'],
  },
  {
    id: 10,
    name: 'Cyberpunk Alley Kit',
    title: 'Cyberpunk Alley Kit',
    price: '$52.00',
    priceValue: 52,
    likes: 1892,
    rating: 4.9,
    reviews: 214,
    downloads: 742,
    views: '47.2k',
    creator: 'Maya Nodes',
    verified: true,
    category: 'Environment',
    image: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.lantern,
    featured: true,
    trending: true,
    staffPick: true,
    description:
      'A neon-lit modular alley kit with storefronts, cables, signage, decals, and optimized collision meshes.',
    polygons: 28700,
    vertices: 23600,
    textures: '4K PBR',
    formats: '.GLB, .FBX, .OBJ, .BLEND',
    fileTypes: ['GLB', 'FBX', 'OBJ', 'BLEND'],
    rigged: false,
    animated: true,
    lowPoly: false,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-05-01',
    tags: ['Cyberpunk', 'Environment', 'Modular', 'Animated', 'PBR'],
  },
  {
    id: 11,
    name: 'Stylized Market Props',
    title: 'Stylized Market Props',
    price: '$18.00',
    priceValue: 18,
    likes: 612,
    rating: 4.6,
    reviews: 49,
    downloads: 932,
    views: '11.9k',
    creator: 'Aria Voxel',
    verified: true,
    category: 'Props',
    image: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.avocado,
    featured: false,
    trending: false,
    staffPick: false,
    description:
      'A bright set of barrels, crates, cloth stalls, baskets, and coin props for cozy town scenes and RPG hubs.',
    polygons: 6100,
    vertices: 4800,
    textures: '2K PBR',
    formats: '.GLB, .FBX, .OBJ',
    fileTypes: ['GLB', 'FBX', 'OBJ'],
    rigged: false,
    animated: false,
    lowPoly: true,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-02-26',
    tags: ['Props', 'Market', 'Stylized', 'Low Poly'],
  },
  {
    id: 12,
    name: 'Ancient Temple Entrance',
    title: 'Ancient Temple Entrance',
    price: '$36.00',
    priceValue: 36,
    likes: 990,
    rating: 4.8,
    reviews: 88,
    downloads: 584,
    views: '26.6k',
    creator: 'Niko Worlds',
    verified: true,
    category: 'Environment',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1000&q=82',
    modelUrl: sampleModels.box,
    featured: true,
    trending: false,
    staffPick: true,
    description:
      'A cinematic temple facade with modular columns, baked vertex color dirt, and foliage-friendly material groups.',
    polygons: 19600,
    vertices: 15100,
    textures: '4K PBR',
    formats: '.GLB, .FBX, .OBJ, .USDZ',
    fileTypes: ['GLB', 'FBX', 'OBJ', 'USDZ'],
    rigged: false,
    animated: false,
    lowPoly: false,
    pbr: true,
    gameReady: true,
    license: 'Royalty-free commercial',
    updatedAt: '2026-04-14',
    tags: ['Temple', 'Ancient', 'Environment', 'PBR'],
  },
];

export const CREATORS = [
  {
    id: 1,
    name: 'Kenji Makes',
    handle: '@kenjimakes',
    initial: 'K',
    bio: 'Sci-fi vehicles and hard-surface props for indie games.',
    models: 2,
    modelsCount: 2,
    sales: 443,
    followers: '18.2k',
    rating: 4.8,
    verified: true,
    location: 'Tokyo, Japan',
    joined: 'February 2024',
    specialty: 'Hard Surface',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80',
    banner: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 2,
    name: 'Sofia Beasts',
    handle: '@sofiabeasts',
    initial: 'S',
    bio: 'Stylized creatures and friendly monsters with production-ready rigs.',
    models: 1,
    modelsCount: 1,
    sales: 421,
    followers: '12.7k',
    rating: 4.9,
    verified: true,
    location: 'Lisbon, Portugal',
    joined: 'March 2024',
    specialty: 'Creatures',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=240&q=80',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 3,
    name: 'Omar Builds',
    handle: '@omarbuilds',
    initial: 'O',
    bio: 'Architectural and environment kits for game worlds and virtual tabletop scenes.',
    models: 2,
    modelsCount: 2,
    sales: 375,
    followers: '10.4k',
    rating: 4.7,
    verified: true,
    location: 'Cairo, Egypt',
    joined: 'January 2024',
    specialty: 'Modular Kits',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&q=80',
    banner: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 4,
    name: 'Lina Forge',
    handle: '@linaforge',
    initial: 'L',
    bio: 'Hand-painted weapons, fantasy gear, and compact VFX-friendly props.',
    models: 2,
    modelsCount: 2,
    sales: 271,
    followers: '8.9k',
    rating: 4.7,
    verified: true,
    location: 'Prague, Czechia',
    joined: 'May 2024',
    specialty: 'Weapons',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80',
    banner: 'https://images.unsplash.com/photo-1605106702734-205df224ecce?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 5,
    name: 'Aria Voxel',
    handle: '@ariavoxel',
    initial: 'A',
    bio: 'Stylized character artist with a love for readable silhouettes and low-poly heroes.',
    models: 2,
    modelsCount: 2,
    sales: 238,
    followers: '7.6k',
    rating: 4.6,
    verified: true,
    location: 'Vancouver, Canada',
    joined: 'June 2024',
    specialty: 'Characters',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=240&q=80',
    banner: 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 6,
    name: 'Ravi Craft',
    handle: '@ravicraft',
    initial: 'R',
    bio: 'Indie game-ready props with cozy shapes, clean pivots, and efficient texture sets.',
    models: 1,
    modelsCount: 1,
    sales: 52,
    followers: '2.1k',
    rating: 4.4,
    verified: false,
    location: 'Bengaluru, India',
    joined: 'August 2024',
    specialty: 'Props',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=240&q=80',
    banner: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 7,
    name: 'Maya Nodes',
    handle: '@mayanodes',
    initial: 'M',
    bio: 'Neon environments, shader-friendly kits, and cinematic world-building packs.',
    models: 1,
    modelsCount: 1,
    sales: 389,
    followers: '15.1k',
    rating: 4.9,
    verified: true,
    location: 'Berlin, Germany',
    joined: 'April 2024',
    specialty: 'Cyberpunk Environments',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=240&q=80',
    banner: 'https://images.unsplash.com/photo-1484950763426-56b5bf172dbb?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 8,
    name: 'Niko Worlds',
    handle: '@nikoworlds',
    initial: 'N',
    bio: 'Ancient worlds, ruins, temple kits, and cinematic terrain dressing.',
    models: 1,
    modelsCount: 1,
    sales: 154,
    followers: '5.8k',
    rating: 4.8,
    verified: true,
    location: 'Athens, Greece',
    joined: 'September 2024',
    specialty: 'Ruins',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=240&q=80',
    banner: 'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?auto=format&fit=crop&w=1600&q=80',
  },
];

export const CATEGORIES = [
  { name: 'Characters', count: 2, description: 'Heroes, NPCs, creatures, and rigged avatars' },
  { name: 'Vehicles', count: 2, description: 'Cars, spacecraft, aircraft, and ships' },
  { name: 'Weapons', count: 2, description: 'Melee, ranged, fantasy, and sci-fi gear' },
  { name: 'Environment', count: 5, description: 'Scenes, architecture, terrain, and modular kits' },
  { name: 'Creatures', count: 1, description: 'Stylized beasts and fantasy wildlife' },
  { name: 'Props', count: 1, description: 'Reusable scene objects and set dressing' },
];

export const COLLECTIONS = [
  {
    id: 'starter-rpg',
    name: 'Indie RPG Starter Pack',
    description: 'Characters, market props, weapons, and fantasy environment pieces for a playable vertical slice.',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=82',
    modelIds: [4, 6, 8, 11, 12],
  },
  {
    id: 'sci-fi-prototype',
    name: 'Sci-Fi Prototype Kit',
    description: 'Fast blockout and production assets for ships, robots, neon alleys, and energy weapons.',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=82',
    modelIds: [3, 7, 9, 10],
  },
  {
    id: 'world-builder',
    name: 'World Builder Essentials',
    description: 'Modular environment staples for teams building explorable spaces quickly.',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=82',
    modelIds: [2, 8, 10, 12],
  },
];

export const TRENDING_SEARCHES = [
  'cyberpunk kit',
  'rigged character',
  'low poly fantasy',
  'pbr weapon',
  'modular castle',
  'animated robot',
];

export const SEARCH_HISTORY_DEFAULT = ['spaceship', 'castle tower', 'market props'];

export const ARTICLES = [
  {
    id: 'optimize-3d-assets',
    title: 'How to Evaluate a Game-Ready 3D Asset Before Purchase',
    excerpt: 'A practical checklist for topology, pivots, material sets, texture density, and licensing.',
    date: 'May 2, 2026',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&w=900&q=82',
  },
  {
    id: 'creator-storefront',
    title: 'Designing a Creator Storefront That Converts',
    excerpt: 'What buyers scan first and how to present packs, previews, updates, and support promises.',
    date: 'April 18, 2026',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=82',
  },
  {
    id: 'render-preview',
    title: 'Better 3D Preview Scenes for Marketplace Assets',
    excerpt: 'Lighting, material overrides, camera defaults, and how to help buyers inspect models quickly.',
    date: 'April 9, 2026',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?auto=format&fit=crop&w=900&q=82',
  },
];

export const FAQS = [
  {
    question: 'Can I use purchased assets in commercial games?',
    answer:
      'Yes. Marketplace assets use a royalty-free commercial license unless a product page states otherwise.',
  },
  {
    question: 'Do models include source files?',
    answer:
      'Most listings include GLB, FBX, and OBJ files. Some premium packs also include Blender, USDZ, texture sources, and LOD exports.',
  },
  {
    question: 'How do I request support from a creator?',
    answer:
      'Open the model detail page, check the creator profile, and use the support action. Purchase history keeps the asset and creator contact in one place.',
  },
  {
    question: 'Can creators upload animated models?',
    answer:
      'Yes. Uploads can include animation clips, rig notes, texture maps, preview images, and technical metadata.',
  },
];

export const COMMUNITY_POSTS = [
  {
    id: 1,
    creator: 'Sofia Beasts',
    title: 'Dragon Rider Prototype',
    image: 'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?auto=format&fit=crop&w=900&q=82',
    likes: 842,
  },
  {
    id: 2,
    creator: 'Maya Nodes',
    title: 'Neon Rain Lighting Pass',
    image: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=82',
    likes: 1196,
  },
  {
    id: 3,
    creator: 'Omar Builds',
    title: 'Castle Courtyard Kitbash',
    image: 'https://images.unsplash.com/photo-1520637836862-4d197d17c90a?auto=format&fit=crop&w=900&q=82',
    likes: 621,
  },
];

export const SUPPORT_TOPICS = [
  'Licensing and invoices',
  'Model format compatibility',
  'Creator payouts',
  'Refund eligibility',
  'Upload review guidelines',
  'Account security',
];
